/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 43a4b67e26bf54bdbd3dd3579f2f347f)
interface __BaseEnv_Env {
	ChatAgent: DurableObjectNamespace<import("./src/index").ChatAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
