/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 47528fb042c2cfc191e65469781ac9ed)
interface __BaseEnv_Env {
	ChatAgent: DurableObjectNamespace<import("./src/index").ChatAgent>;
	TaskAgent: DurableObjectNamespace<import("./src/index").TaskAgent>;
	TaskWorkflow: Workflow<Parameters<import("./src/index").TaskWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatAgent" | "TaskAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
